# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ed3b875777f18a49000de1d9537ef12fab96b9278da488a548c20d97ab8121c823085a96ba6f963cb0219580a578343f185d1f39e96748913a6ad15d713af790

test:
  secret_key_base: cc52d7a8a66b54e54105b600a46e410a8f2884d3081919075ec3a2c1216ac718f94c4d5ed9b94a1360d0c9247386c59c62ea8337073411ea45d285339c3a02d6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
